"""PR Newsjacking Crew — orchestrates the four-agent pipeline per client.

PR-6 (News Analyst) → PR-7 (Media List) → PR-7s (Web Supplement) → PR-8 (Pitch Drafter)
"""

import html as html_mod
import json
import os
import traceback
from datetime import date, timezone, datetime

import httpx
from crewai import Crew, Process
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build

from agents import build_media_list_builder, build_news_analyst, build_pitch_drafter, build_web_search_supplement
from config import SLACK_BOT_TOKEN, ClientConfig, load_clients
from filters import articles_to_payload, fetch_and_filter
from tasks import build_pr6_task, build_pr7_supplement_task, build_pr7_task, build_pr8_task

ADC_PATH = os.path.expanduser("~/.config/gcloud/application_default_credentials.json")
PITCH_DOCS_FOLDER_ID = os.environ.get("PITCH_DOCS_FOLDER_ID", "YOUR_GOOGLE_DRIVE_FOLDER_ID")
SLACK_NOTIFY_USER_ID = os.environ.get("SLACK_NOTIFY_USER_ID", "YOUR_SLACK_USER_ID")


def _get_drive_service():
    creds = Credentials.from_authorized_user_file(
        ADC_PATH, scopes=["https://www.googleapis.com/auth/drive.file"],
    )
    return build("drive", "v3", credentials=creds)


def _format_pitch_doc(client: ClientConfig, data: dict) -> str:
    today = date.today().isoformat()
    e = html_mod.escape
    parts = [
        "<html><body>",
        f"<h1>{e(client.name)} Newsjacking Pitches</h1>",
        f"<p>{today} · Generated by PR Newsjacking Pipeline</p>",
        "<hr>",
    ]

    for num, angle in enumerate(data.get("angles", []), 1):
        headline = e(angle.get("headline", "?"))
        score = angle.get("relevance_score", "?")
        outlet = e(angle.get("outlet", "?"))
        source_url = angle.get("source_url", "")
        client_angle = e(angle.get("client_angle", ""))
        talking_point = e(angle.get("talking_point", ""))

        parts.extend([
            f"<h2>Angle {num}: [{score}/10] {headline}</h2>",
            f"<p><b>Source:</b> {outlet}<br>",
            f"<b>URL:</b> <a href=\"{source_url}\">{e(source_url)}</a></p>",
            f"<p><b>Client Angle:</b> {client_angle}</p>",
            f"<p><b>Talking Point:</b> {talking_point}</p>",
        ])

        for r_num, r in enumerate(angle.get("media_list", []), 1):
            name = e(r.get("reporter", "?"))
            r_outlet = e(r.get("outlet", "?"))
            beat = e(r.get("beat", "?"))
            email = e(r.get("email", "not_available"))
            verified = "Verified" if r.get("verified") else "Unverified"
            subject = e(r.get("subject_line", ""))
            pitch_html = e(r.get("pitch", "")).replace("\n\n", "</p><p>").replace("\n", "<br>")

            parts.extend([
                f"<h3>Reporter {r_num}: {name}</h3>",
                f"<p><b>Outlet:</b> {r_outlet} | <b>Beat:</b> {beat} | "
                f"<b>Email:</b> {email} | <b>Status:</b> {verified}</p>",
                f"<p><b>Subject:</b> {subject}</p>",
                f"<p>{pitch_html}</p>",
                "<hr>",
            ])

    parts.append("</body></html>")
    return "\n".join(parts)


def _create_pitch_doc(client: ClientConfig, data: dict) -> str | None:
    try:
        from googleapiclient.http import MediaInMemoryUpload
        drive = _get_drive_service()
        today = date.today().isoformat()
        title = f"{client.name} Newsjacking Pitches — {today}"
        content = _format_pitch_doc(client, data)
        media = MediaInMemoryUpload(content.encode("utf-8"), mimetype="text/html", resumable=False)
        doc_file = drive.files().create(
            body={"name": title, "parents": [PITCH_DOCS_FOLDER_ID],
                  "mimeType": "application/vnd.google-apps.document"},
            media_body=media, fields="id, webViewLink",
        ).execute()
        return doc_file["webViewLink"]
    except Exception as e:
        print(f"[crew] Google Doc creation error: {e}")
        return None


def _post_slack(channel: str, text: str) -> None:
    httpx.post(
        "https://slack.com/api/chat.postMessage",
        headers={"Authorization": f"Bearer {SLACK_BOT_TOKEN}", "Content-Type": "application/json"},
        json={"channel": channel, "text": text, "unfurl_links": False},
        timeout=10,
    )


def run_client(client: ClientConfig) -> dict:
    """Run the full newsjacking pipeline for a single client."""
    today = date.today().isoformat()
    filter_result = fetch_and_filter(client)

    if filter_result.status == "NO_NEWS":
        _post_slack(client.output_channel_id,
                    f"📭 *{client.name}* — No qualifying articles found in the past 7 days.")
        return {"client": client.name, "status": "NO_NEWS", "run_date": today}

    news_analyst = build_news_analyst(client)
    media_builder = build_media_list_builder(client)
    web_supplement = build_web_search_supplement(client)
    pitch_drafter = build_pitch_drafter(client)

    pr6_task = build_pr6_task(news_analyst, client, filter_result.articles)
    pr7_task = build_pr7_task(media_builder, client)
    pr7_task.context = [pr6_task]
    pr7s_task = build_pr7_supplement_task(web_supplement, client)
    pr7s_task.context = [pr7_task]
    pr8_task = build_pr8_task(pitch_drafter, client)
    pr8_task.context = [pr7_task, pr7s_task]

    crew = Crew(
        agents=[news_analyst, media_builder, web_supplement, pitch_drafter],
        tasks=[pr6_task, pr7_task, pr7s_task, pr8_task],
        process=Process.sequential,
        verbose=False,
    )

    try:
        result = crew.kickoff()
    except Exception as e:
        error_msg = f"{type(e).__name__}: {e}\n{traceback.format_exc()[-500:]}"
        _post_slack(client.output_channel_id,
                    f"🔴 *{client.name}* — ERROR\n```{error_msg[:1000]}```\n<@{SLACK_NOTIFY_USER_ID}>")
        return {"client": client.name, "status": "ERROR", "run_date": today, "error": error_msg}

    output_text = str(result)

    if "NO_QUALIFYING_ANGLES" in output_text:
        _post_slack(client.output_channel_id,
                    f"🟡 *{client.name}* — No Qualifying Angles\n"
                    f"News found but nothing scored 7/10+.")
        return {"client": client.name, "status": "NO_QUALIFYING_ANGLES", "run_date": today}

    try:
        start = output_text.index("{")
        end = output_text.rindex("}") + 1
        raw_json = output_text[start:end]
        try:
            parsed = json.loads(raw_json)
        except json.JSONDecodeError:
            import json_repair
            raw_json = json_repair.repair_json(raw_json)
            parsed = json.loads(raw_json)
    except Exception:
        parsed = None

    if parsed and parsed.get("angles"):
        doc_url = _create_pitch_doc(client, parsed)
        angles = parsed["angles"]
        angle_blocks = []
        for a in angles:
            reporters = " · ".join(
                f"{r.get('reporter', '?')} ({r.get('outlet', '?')})"
                for r in a.get("media_list", [])
            )
            angle_blocks.append(
                f"*[{a.get('relevance_score', '?')}/10]* {a.get('headline', '?')}\n"
                f"Source: {a.get('outlet', '?')}\nReporters: {reporters}"
            )
        doc_line = f"\n📄 <{doc_url}|View full pitches>" if doc_url else ""
        _post_slack(
            client.output_channel_id,
            f"✅ *{client.name}* — {len(angles)} Angle{'s' if len(angles) != 1 else ''} Ready\n\n"
            f"{chr(10).join(angle_blocks)}\n\nReview and approve before pitching.{doc_line}"
        )
        return {"client": client.name, "status": "SUCCESS", "run_date": today}
    else:
        _post_slack(client.output_channel_id,
                    f"🟡 *{client.name}* — No Qualifying Angles\nNews found but nothing scored 7/10+.")
        return {"client": client.name, "status": "NO_QUALIFYING_ANGLES", "run_date": today}


def run_all_clients(client_filter: str | None = None) -> list[dict]:
    clients = load_clients()
    if client_filter:
        clients = [c for c in clients if client_filter.lower() in c.name.lower()]

    results = []
    for i, client in enumerate(clients, 1):
        print(f"[{datetime.now(timezone.utc).strftime('%H:%M:%S')}] [{i}/{len(clients)}] {client.name}")
        result = run_client(client)
        print(f"  → {result['status']}")
        results.append(result)

    return results
